[tool.poetry]
name = "fastapi-course"
version = "0.1.0"
description = ""
authors = ["Damien Chauvet <chauvet.damien@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.115.0"
uvicorn = "^0.31.1"
pytest = "^8.3.3"
httpx = "^0.27.2"
slowapi = "^0.1.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
